### PR TITLE
feat!: refactor library architecture

### PR DESCRIPTION
**Pull request by iAmMichaelConnor**
# Description
As per https://github.com/noir-lang/noir-bignum/pull/27

This version passes MOD_BITS around as a generic, instead of as a constant, which is needed for the latest noir release.

### CODE REVIEW

**Comment by iAmMichaelConnor** [comment]
The tests fail because this PR is only compatible with the latest version of aztec-packages nargo.

**Comment by iAmMichaelConnor** [comment]
In my defense, I just ran `nargo fmt` and it made 3000 extra line changes.

**Comment by TomAFrench** [comment]
Can you update the CI to run on the new minimum noir version?

**Comment by kashbrti** [comment]
just change the version in test.yml to 0.36.0 and the noir tests should pass

**Review by TomAFrench — APPROVED** [review]

**Pull request merged**
